

CREATE TABLE orders(

    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (order_id)
)


CREATE TABLE order_items(

    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY (order_item_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    --FOREIGN KEY (product_id) REFERENCES products(product_id)
)